name: example
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  vector_math: ^2.1.4
  dev: ^1.0.0

  protobuf: ^4.1.0
  connectrpc: ^1.0.0
  http: ^1.4.0
  provider: ^6.1.5
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.3
  share_plus: ^12.0.1
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  google_fonts: ^6.2.1
  flutter_svg: ^2.1.0

  fl_chart: ^1.0.0

  image_picker: ^1.1.2

  mask_text_input_formatter: ^2.9.0

  moonspace:
    path: ../
  moon_debug:
    path: ../moon_debug
  flutter_custom_carousel: ^0.1.0+1
  smooth_sheets: ^0.15.0
  auto_size_text: ^3.0.0
  flutter_layout_grid: ^2.0.8
  math_expressions: ^3.1.0
  window_size: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.7.1
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3
  custom_lint: ^0.8.0
  go_router_builder: ^4.1.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/desserts/
    - assets/location/Paris/
    - assets/location/London/
    - assets/location/Pisa/
    - assets/location/Budapest/

    - assets/activities.json
    - assets/destinations.json
    - assets/rankone.json
    - assets/funko.json

    - assets/images/card_deck/
    - assets/images/cover_slider/
    - assets/images/digital_wallet/
    - assets/images/circular_menu/
    - assets/images/record_box/
