name: moonspace
description: MoonSpace
version: 0.0.1
homepage: https://github.com/CodeHariK/MoonSpace

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.16.0

  go_router: ^16.3.0

  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3

  feedback: ^3.2.0

  shared_preferences: ^2.5.3

  flutter_animate: ^4.5.2

  flutter_custom_carousel: ^0.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  riverpod_generator: ^3.0.3
  build_runner: ^2.7.1
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.3

flutter:
  generate: true
