name: moon_debug
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/CodeHariK/MoonSpace
publish_to: "none"

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  accessibility_tools: ^2.7.1

  path_provider: ^2.1.5
  device_frame_plus: ^1.5.0

  moonspace:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
